p = r'c:\Users\STD2568\Desktop\oren-cohen-bot\static\training.html'
lines = []
lines.append('<div class="section" id="sehel"><div class="section-title">🔗 אינטגרציה עם שכל CRM</div>')
lines.append('<div class="section-sub">כל שיחה שמסתיימת — נשמרת אוטומטית בשכל</div>')
lines.append('<div class="grid">')
lines.append('<div class="card"><h3>📝 הערה אוטומטית</h3><p>בסיום כל שיחה — הבוט מוסיף הערה לכרטיס הלקוח בשכל עם תמליל מלא, סטטוס ותאריך.</p></div>')
lines.append('<div class="card"><h3>🏷️ תגיות אוטומטיות</h3><p>כל ליד מקבל תגיות: ליד חם / ליד בינוני / ליד קר. לידים שלא ענו מקבלים תגית "אין מענה".</p></div>')
lines.append('<div class="card"><h3>👤 שיוך לסוכן</h3><p>הליד משויך אוטומטית לסוכן הנכון לפי המחלקה — פרויקטים לאהרון, יד 2 לבועז, אנגלית לליסה.</p></div>')
lines.append('<div class="card"><h3>⚠️ לידים תקועים</h3><p>אם לקוח ענה אבל השיחה לא הסתיימה תוך שעתיים — הבוט שולח את הליד לשכל אוטומטית.</p></div>')
lines.append('</div>')
lines.append('<div class="alert-g">✅ הבוט לעולם לא יוצר כרטיס כפול — הוא מזהה לפי מספר טלפון ומוסיף הערה לכרטיס הקיים.</div></div>')
lines.append('<div class="section" id="reminders"><div class="section-title">⏰ תזכורות ודוחות אוטומטיים</div>')
lines.append('<div class="section-sub">הבוט עובד בשבילכם גם ברקע</div>')
lines.append('<div class="alert-g">🌅 כל יום ראשון עד חמישי בשעה 9:00 — כל סוכן מקבל תזכורת בוקר אישית בוואטסאפ. שישי ושבת — אין שליחה.</div>')
lines.append('<div class="grid" style="margin-top:16px">')
lines.append('<div class="card"><h3>📬 דוח יומי למייל</h3><p>כל 24 שעות — הסוכן מקבל דוח מייל עם רשימת הלקוחות שנשלחו, מי ענה ומי הועבר.</p></div>')
lines.append('<div class="card"><h3>📧 התראת לקוח רלוונטי</h3><p>ברגע שלקוח מסמן handoff — הסוכן מקבל מייל מיידי עם שם הלקוח, טלפון ותמליל השיחה.</p></div>')
lines.append('<div class="card"><h3>📮 סקירת אימיילים</h3><p>הבוט סורק את תיבת המייל כל 30 שניות ומטפל בפניות שמגיעות במייל — בדיוק כמו בוואטסאפ.</p></div>')
lines.append('</div></div>')
lines.append('<div class="section" id="tips"><div class="section-title">💡 טיפים חשובים לסוכן</div>')
lines.append('<div class="section-sub">מה לדעת ומה לא לעשות</div>')
lines.append('<div class="grid">')
lines.append('<div class="card"><h3>✅ הבוט לא נותן מחירים</h3><p>אם לקוח שואל על מחיר — הבוט תמיד מפנה לסוכן. לעולם לא ינקוב בסכום. זה מכוון.</p></div>')
lines.append('<div class="card"><h3>✅ הבוט לא שואל שאלות</h3><p>הבוט לא שואל על תקציב, אזור, חדרים. הוא רק עונה ומעביר. השאלות — תפקיד הסוכן.</p></div>')
lines.append('<div class="card"><h3>✅ הבוט לא מתאם פגישות</h3><p>הבוט לא שואל מתי נוח ולא מתאם שיחה. הסוכן יוצר קשר ביוזמתו.</p></div>')
lines.append('<div class="card"><h3>⚠️ אל תשלחו לקוח פעמיים</h3><p>אם לקוח כבר קיבל הודעה — אל תשלחו שוב. הבוט חוסם כפילויות.</p></div>')
lines.append('<div class="card"><h3>⚠️ לקוח שכבר בקשר עם סוכן</h3><p>אם לקוח כותב "אני בקשר עם אהרון" — הבוט עונה "איזה כיף לשמוע! בהצלחה 😊" וסוגר.</p></div>')
lines.append('<div class="card"><h3>⚠️ שאלות שלא קשורות לנדל"ן</h3><p>אם לקוח שואל על מזג אוויר / פוליטיקה — הבוט מסרב בנימוס ומחזיר לנדל"ן.</p></div>')
lines.append('</div>')
lines.append('<div style="margin-top:28px"><div class="section-title" style="font-size:20px;margin-bottom:14px">🗣️ עדויות מהשטח</div>')
lines.append('<div class="tst"><p>"הבוט ענה ללקוח בשעה 2 בלילה. בבוקר קיבלתי מייל שהלקוח רלוונטי. התקשרתי ב-9:00 וסגרנו פגישה. בלי הבוט הייתי מפספס אותו לגמרי."</p><div class="auth">— סוכן מחלקת פרויקטים</div></div>')
lines.append('<div class="tst"><p>"שלחתי 80 לקוחות ישנים. 23 ענו חיובית. הבוט ניהל את כולם בו-זמנית בלי שאני צריך לעשות כלום. קיבלתי 23 התראות מייל עם תמליל מוכן."</p><div class="auth">— סוכן מחלקת יד 2</div></div>')
lines.append('<div class="tst"><p>"לקוח שלא ענה לי 3 שנים — ענה לבוט תוך 10 דקות. כנראה שהודעת וואטסאפ מ\'דניאל\' נראית אחרת מהתקשרות של סוכן."</p><div class="auth">— סוכן בכיר</div></div>')
lines.append('</div></div>')
lines.append('<div class="section"><div class="section-title">🚀 איך מתחילים — 4 צעדים</div>')
lines.append('<div class="steps">')
lines.append('<div class="step"><div class="num">1</div><div><h4>הכינו רשימת לקוחות</h4><p>Excel עם עמודות: שם, טלפון, שם פרויקט. טלפון בפורמט: 05XXXXXXXX</p></div></div>')
lines.append('<div class="step"><div class="num">2</div><div><h4>העלו את הרשימה</h4><p>דרך ממשק הסוכן — לחצו "שלח קמפיין" והעלו את הקובץ. הבוט מתחיל לשלוח אוטומטית.</p></div></div>')
lines.append('<div class="step"><div class="num">3</div><div><h4>עקבו בדשבורד</h4><p>פתחו את הדשבורד ועקבו בזמן אמת מי ענה ומי הועבר אליכם.</p></div></div>')
lines.append('<div class="step"><div class="num">4</div><div><h4>חזרו ללקוחות שהועברו</h4><p>כל לקוח שהועבר — מקבלים מייל עם תמליל. התקשרו אליו בהקדם האפשרי.</p></div></div>')
lines.append('</div></div>')
lines.append('</div>')
lines.append('<footer><p>🤖 בוט דניאל | אורן כהן גרופ | מסמך הכשרה פנימי</p><p style="margin-top:8px">לשאלות — פנו לטליה</p></footer>')
lines.append('</body></html>')
with open(p, 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines))
